### ISSUE TITLE
Actividad 6 Realidad Aumentada de objeto 3d con animacion

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-promastergamer#1]

**Comment by FedericoVictorianoSierra** [comment]
[Actividad 6 Animación.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-promastergamer/files/14705577/Actividad.6.Animacion.pdf)

**Comment by NoeliaGlez** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
